import rtconfig
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, str(Dir('#'))]
src     = Split("""
main.c
ble_detect.c
parse_cmd_line.c
dev_model/linkkit_example_solo.c
dev_model/cJSON.c
""")


CPPPATH += [cwd + '/dev_model']

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
